[[redirects]]
  from = "/packs"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/gallery"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200
